source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'sqlite3' # Database driver gem - autoset
gem 'jquery-rails'
gem 'simple_form'
gem 'money_column'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'ruby-openid'

group :assets do
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'
  gem 'factory_girl'
end

group :test do
  gem 'simplecov', :require => false
end