source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'sqlite3' # Database driver gem - autoset
gem 'jquery-rails'
gem 'simple_form'
gem 'money'

group :assets do
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'
end
