source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'sqlite3'
gem 'jquery-rails'

group :assets do
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'
end